# Working with CSV files

## Extracting Data from CSV file

In [1]:
import numpy as np

Downloading a climate file containing climate measurements(temp, humi, rain)

In [2]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7ad706002290>)

Extract the data as numpy array

In [6]:
cl_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

## Analysing the data

In [7]:
cl_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [9]:
cl_data.shape

(10000, 3)

In [11]:
weight = np.array([0.1, 0.2, 0.3])

In [12]:
yield_data= cl_data @ weight

In [13]:
yield_data

array([47.4, 37.9, 38. , ..., 39.7, 48.5, 39.8])

In [14]:
yield_data.shape

(10000,)

In [16]:
cl_result = np.concatenate((cl_data, yield_data.reshape(10000, 1)), axis=1)

In [17]:
cl_result

array([[25. , 76. , 99. , 47.4],
       [39. , 65. , 70. , 37.9],
       [59. , 45. , 77. , 38. ],
       ...,
       [99. , 62. , 58. , 39.7],
       [70. , 71. , 91. , 48.5],
       [92. , 39. , 76. , 39.8]])

## Saving back the data into a file

In [24]:
np.savetxt('climate_results.txt',
           cl_result,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples',
           comments='')