# Arrays in Numpy

##Creating n-dimensional Arrays

In [38]:
import numpy as np

In [39]:
arr = np.array([1, 2, 3, 4, 5]) #list as parameter

print(arr)

[1 2 3 4 5]


In [30]:
arr = np.array((1, 2, 3, 4, 5)) #tuple as parameter

print(arr)

[1 2 3 4 5]


In [31]:
arr0= np.array(42) #0-dimensional array

print(arr0)

42


In [32]:
arr1 = np.array([1, 2, 3, 4, 5]) #1-dimensional array

print(arr1)

[1 2 3 4 5]


In [33]:
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]]) #2-dimensional array

print(arr2)

[[1 2 3]
 [4 5 6]]


In [34]:
arr3 = np.array([[[1, 2, 3],[4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3-dimensional array

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [35]:
print(arr0.ndim) #checking dimensions
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [36]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Array Indexing

In [43]:
arr = np.array([1, 2, 3, 4]) #accessing elements in 1d array

print(arr[3])

4


In [44]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]]) #accessing elements in 2d array

print(arr[1, 4])

10


In [45]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #accessing elements in 3d array

print(arr[0, 1, 2])

6


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]) # array slicing

print(arr[1:5])

[2 3 4 5]


In [51]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [56]:
#datatypes while creating array: i,f,S etc.,
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [57]:
arr = np.array([1, 0, 3]) # converting the existing into other datatype

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [58]:
#COPY in numpy array
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [59]:
#VIEW in numpy array
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [60]:
#Checking whether array own the data
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[42  2  3  4  5]
