#Array/Matrix operaitons using numpy

In [2]:
import numpy as np

In [3]:
#shape of the array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [6]:
#reshape of array from 1-d tp 2-d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
#reshape of array from 1-d tp 3-d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
#unknown dimension :-1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,])

newarr = arr.reshape(2,-1, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
#iterating array with different datatypes using op_dtypes
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [28]:
#enumerate
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [34]:
# arrays JOIN
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
#join using STACK :  hstack(), vstack(), dstack()
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [46]:
# array_split() : hsplit(), vsplit(), dsplit()
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]


In [58]:
# searching elements in np array
arr = np.array([1, 2, 5, 4, 5, 6, 7, 8])

x = np.searchsorted(arr,4)
y=np.where(arr==4)
print(x)
print(y)

2
(array([3]),)


In [61]:
#Filtering array
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
